### ISSUE TITLE
[tracking] Mention Sponsors in TWIRF

### ISSUE THREAD

**Issue by gandro** [RustFestEU/rome.rustfest.eu#37]
- [x] Threema (silver)
- [x] Kodebox (silver)
- [-] Parity (gold)
  - [ ] [Blog post on day of Event](https://github.com/RustFestEU/blog.rustfest.eu/pull/76)
- [x] Cryptape (gold)
  - [ ] [Blog post on day of Event](https://github.com/RustFestEU/blog.rustfest.eu/pull/69)
- [ ] Mozilla (unconfirmed gold, also gets blog post)
  - [ ] Blog post on day of Event
- [ ] Baidu (silver)
- [ ] 1aim (Gold)
  - [ ] Blog post on day of Event

**Comment by apiraino** [comment]
Media coverage for Cryptape is [here](https://docs.google.com/document/d/1TLaAVFbdgWkhSHH0HeopjfItUUbBaRh5LgpuRuk0EuI).

**Comment by skade** [comment]
We should make sure that the blog posts on the day of the event do not go out as three newsletters. That would be annoying.

**Comment by apiraino** [comment]
@gandro updated the list adding Baidu

**Comment by Hoverbear** [comment]
Added 1aim
